events {}

http {
    upstream frontend {
        server frontend:80;
    }

    upstream admin_dashboard {
        server admin-dashboard:80;
    }

    upstream auth_service {
        server auth:3000;
    }

    upstream panier_service {
        server panier:8000;
    }

    server {
        listen 80;

        # Frontend Angular
        location / {
            proxy_pass http://frontend/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Admin Dashboard React/Vite accessible via /shop/
        location /shop/ {
            rewrite ^/shop/(.*)$ /$1 break;
            proxy_pass http://admin_dashboard/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /panier/ {
            rewrite ^/panier(/.*)$ $1 break;
            proxy_pass http://panier:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/healthcheck {
            return 200 '{"status": "nginx OK"}';
            add_header Content-Type application/json;
        }
    }
}
